version: "3"
services:
  db:
    platform: linux/x86_64
    image: postgres:13
    container_name: gocore.db
    ports:
      - "5491:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_DATABASE: gocore
      POSTGRES_USER: gocore
      POSTGRES_PASSWORD: gocore123
      TZ: UTC
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
